const skills = [
  "HTML/CSS/JS",
  "Reactjs",
  "Redux",
  "Tailwindcss",
  "Bootstrap",
  "SCSS(Sass)",
  "Webpack",
  "Webpack dev server",
  "Git",
  "OOP",
  "express.js",
  "Mongodb",
  "sqlite",
  "nginx",
  "apache",
  "adaptive layout",
  "cross-browser layout",
  "JSON",
  "Python 3",
  "Django",
  "BeautifulSoup4",
  "requests",
  "opencv",
  "Tensorflow (still learning)",
  "matplotlib",
  "pandas",
  "numpy",
];

export default skills;
